#! /bin/sh

cargo build --release --target arm-unknown-linux-gnueabihf && \
rsync target/arm-unknown-linux-gnueabihf/release/musicbox musicbox: && \
scp hw_configs/pi-zero-w.json musicbox:data/hwconfig.json
