#! /bin/sh

install_deb() {
  URL=$1
  curl $URL >$TMPDIR/package.deb
  dpkg --extract $TMPDIR/package.deb /Volumes/toolchains/sysroots/$TARGET
  rm $TMPDIR/package.deb
}

install_deb http://archive.raspbian.org/raspbian/pool/main/a/alsa-lib/libasound2_1.1.8-1_armhf.deb
install_deb http://archive.raspbian.org/raspbian/pool/main/a/alsa-lib/libasound2-dev_1.1.8-1_armhf.deb
